version: "3.9"
services:
  redis:
    container_name: redis
    image: redis:alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    volumes:
      - ./_data/redis:/data
      - ./config/redis_cfg/redis.conf:/redis.conf
    command: redis-server /redis.conf
  redisinsight:
    container_name: redisinsight
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"
    volumes:
      - ./_data/data/redisinsight:/db
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./_data/pg_data:/var/lib/postgresql/data
  webapi:
    container_name: webapi
    image: go-api-product:0.1.8
    build: .
    ports:
      - 8080:8080
    restart: always
    environment:
      - PORT=${PORT}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - SECRET_KEY=${SECRET_KEY}
      - APP_ENV=${APP_ENV}
    volumes:
      - "./uploads:/uploads"
      - "./config/acl_model.conf:/config/acl_model.conf"
      - "./config/policy.csv:/config/policy.csv"
    depends_on:
      - db
      - redis
    links:
      - "db:db"
