version: "3.9"
services:
  redis:
    container_name: redis
    image: redis:6.2.6-alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    volumes:
      - ./_data/redis:/data
      - ./config/redis_cfg/redis.conf:/redis.conf
    command: redis-server /redis.conf
  db:
    container_name: postgres
    image: postgres:14.1
    environment:
      POSTGRES_DB: product_shop
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./_data/pg_data:/var/lib/postgresql/data
  webapi:
    container_name: webapi
    image: sing3demons/go-api-product:0.2.1
    ports:
      - 8080:8080
    restart: always
    environment:
      - PORT=8080
      - DATABASE_URL=host=db user=postgres password=12345678 dbname=product_shop port=5432 sslmode=disable TimeZone=Asia/Bangkok
      - SECRET_KEY=${SECRET_KEY}
      - APP_ENV=${APP_ENV}
      - GIN_MODE=${GIN_MODE}
      - REDIS_HOST=redis
    volumes:
      - "./uploads:/uploads"
    depends_on:
      - db
      - redis
    links:
      - "db:db"
