version: "3.1"
services:
  redis:
    container_name: redis
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    volumes:
      - ./_data/redis:/data
      - ./config/redis_cfg/redis.conf:/redis.conf
    command: redis-server /redis.conf
  redisinsight:
    container_name: redisinsight
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"
    volumes:
      - ./_data/data/redisinsight:/db
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./_data/pg_data:/var/lib/postgresql/data
  webapi:
    # build: .
    container_name: webapi
    image: sing3demons/go-api-product:0.1.3
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ".:/app"
      - "./uploads:/uploads"
    restart: always
    depends_on:
      - db
      - redis
    links:
      - "db:db"
  
