version: "3.1"
services:
  redis:
    container_name: redis
    image: redis:alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"
    volumes:
      - ./_data/data/redisinsight:/db
  db:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./_data/pg_data:/var/lib/postgresql/data
  web:
    image: sing3demons/go-api-product:0.1.2
    ports:
      - 8080:8080
    volumes:
      - "./app:/app"
    restart: always
    depends_on:
      - db
      - redis
    links:
      - "db:db"
  # web:
  #   build: .
  #   ports:
  #     - "${PORT}:${PORT}"
  #   volumes:
  #     - ".:/app"
  #   restart: always
  #   depends_on:
  #     - db
  #     - redis
  #   links:
  #     - "db:database"
